server:
  port: 7788
  servlet:
    session:
      timeout: 30m
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 180000
    lettuce:
      pool:
        max-active: 20
        max-wait: 5000ms
        min-idle: 4
        max-idle: 8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    # 空对象 null 不序列化
    defaultPropertyInclusion: NON_EMPTY
    serialization:
      # 日期是否要序列化为数字时间戳
      write_dates_as_timestamps: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
      # 格式化输出
      indent_output: false
      # 枚举输出
      #write_enums_using_index: true
      write_enums_using_to_string: true
    deserialization:
      # 反序列化时候遇到不匹配的属性 是否抛异常
      fail_on_unknown_properties: false
      # 反序列化的时候如果是无效子类型,是否抛出异常
      fail_on_invalid_subtype: false
      # 反序列化时，遇到忽略属性 是否抛出异常
      fail_on_ignored_properties: false
      # 反序列化时，空字符串对于的实例属性为null
      accept_empty_string_as_null_object: true
    parser:
      # 允许C和C++样式注释
      allow_comments: true
      # 允许字段名没有引号
      allow_unquoted_field_names: true
      # 允许单引号
      allow_single_quotes: true
      # 允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
logging:
  charset:
    console: UTF-8
    file: UTF-8
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM}.%i.gz
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /doc
    # 开启Swagger UI界面
#    enabled: true
    disable-swagger-default-url: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
#    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: noob.toolbox.controller
---
customer:
  file-save-path: D:\logs\
spring:
  config:
    activate:
      on-profile: dev
logging:
  file:
    path: D://logs
  level:
    root: INFO
    noob.toolbox: INFO
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
---
customer:
  file-save-path: /var/file/
spring:
  config:
    activate:
      on-profile: pro
logging:
  file:
    path: /var/log/spring
  level:
    root: INFO
    noob.toolbox: debug
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false